### ISSUE TITLE
Documents() function is missing

### ISSUE THREAD

**Issue by sahilpma** [cicanci/fauna-unity#1]
![image](https://user-images.githubusercontent.com/38884892/117485956-a72aa380-af86-11eb-9c47-802f61787c8f.png)

You have provided a wonderful solution. Thanks for this!!!
I found an issue while I was playing around and the Documents function was missing.
https://docs.fauna.com/fauna/current/api/fql/functions/documents?lang=csharp

**Comment by cicanci** [comment]
@sahilpma thank you for your comment :)
This Unity package had the FaunaDB 2.1.0, which was so old that didn't have the `Documents` class. I updated now to FaunaDB 4.0.0-preview (because the official version was not released yet).
You may need to remove and [add back the repository](https://github.com/cicanci/fauna-unity#readme) if you don't see an update in your Unity package manager (or close Unity to update it).

**Comment by sahilpma** [comment]
Thanks
